"""autogenerated by genpy from outdoor_bot/movement_msg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class movement_msg(genpy.Message):
  _md5sum = "f112aa514e85d13579f616bb7596955c"
  _type = "outdoor_bot/movement_msg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string command
int32 distance
int32 angle
int32 map_or_bot
int32 quatX
int32 quatY
int32 quatZ
int32 quatW

"""
  __slots__ = ['command','distance','angle','map_or_bot','quatX','quatY','quatZ','quatW']
  _slot_types = ['string','int32','int32','int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       command,distance,angle,map_or_bot,quatX,quatY,quatZ,quatW

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(movement_msg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.command is None:
        self.command = ''
      if self.distance is None:
        self.distance = 0
      if self.angle is None:
        self.angle = 0
      if self.map_or_bot is None:
        self.map_or_bot = 0
      if self.quatX is None:
        self.quatX = 0
      if self.quatY is None:
        self.quatY = 0
      if self.quatZ is None:
        self.quatZ = 0
      if self.quatW is None:
        self.quatW = 0
    else:
      self.command = ''
      self.distance = 0
      self.angle = 0
      self.map_or_bot = 0
      self.quatX = 0
      self.quatY = 0
      self.quatZ = 0
      self.quatW = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.command
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7i.pack(_x.distance, _x.angle, _x.map_or_bot, _x.quatX, _x.quatY, _x.quatZ, _x.quatW))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.command = str[start:end].decode('utf-8')
      else:
        self.command = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.distance, _x.angle, _x.map_or_bot, _x.quatX, _x.quatY, _x.quatZ, _x.quatW,) = _struct_7i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.command
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7i.pack(_x.distance, _x.angle, _x.map_or_bot, _x.quatX, _x.quatY, _x.quatZ, _x.quatW))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.command = str[start:end].decode('utf-8')
      else:
        self.command = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.distance, _x.angle, _x.map_or_bot, _x.quatX, _x.quatY, _x.quatZ, _x.quatW,) = _struct_7i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_7i = struct.Struct("<7i")
